language: cpp
compiler: clang

addons:
  apt:
    packages:
      - doxygen

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - mkdir html
  - cd build
  - cmake ..
  - cd ..

script:
  - cd build
  - cmake --build .
  - ctest .
  - cd ..
  - cd doc
  - doxygen
  - cd ..

after_success:
  - coveralls --exclude build/CMakeFiles/ --exclude build/gtest/ --exclude gtest/ --exclude build/main/ --exclude main/ --gcov "llvm-cov gcov" --gcov-options '\-lp'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc/_build/html
  on:
    branch: master